# Site settings
title: Paul And All
header-img: img/home-bg.png
email: paulheisele@gmail.com
copyright_name: PaulEisele
description: > # this means to ignore newlines until "baseurl:"
  Bytes and bits in my life. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PaulEisele
learn_profile: PaulEisele
email_username: paulheisele@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
